# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd1eb1f42e85ac6a63189e84020fb94a658abf3e7c29e64814af0c35d2ae9907f880dc5261968844c26effa787975b33f21a140592ca0d9dc193037c68e0c7f
  facebook_app_id: 871284019561971
  facebook_app_secret: f231b1fb384088044a283793cc26432e

test:
  secret_key_base: f13918065946a79cf79d9f8ecddc0116436d3be1c48d9113753d0f67db9a99776daa52050b2ccb1d9f7de2619d24a00d14c704192fe0ae2d0702617d081fe28b
  facebook_app_id: 871284019561971
  facebook_app_secret: f231b1fb384088044a283793cc26432e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
